routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/test', function () {
    return phpinfo();
});

//Auth::routes();
// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/', 'ArticlesController@index')->name('home');
Route::get('/articles/{article}', 'ArticlesController@show')->name('article.show');
Route::get('/articles/tagged/{tag}', 'ArticlesController@filter_tag')->name('article.filter_tag');


Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['web', 'auth']], function ($q) {
    Route::resource('articles', 'Admin\ArticlesController')->except(['index', 'show']);
    Route::post('/images/{image_id}/delete', 'Admin\ArticlesController@delete_img')->name('images.delete');
});


Route::any('{catchall}', function (){
    return redirect()->route('home')->setStatusCode(302);
})->where('catchall', '.*');

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

/**
 * Class Article
 * @package App\Models
 *
 * @property int $id
 * @property string $title
 * @property string $text
 * @property-read User|Model $author
 * @property-read Tag[]|Collection $tags
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 *
 * @method static Builder| Article newModelQuery()
 * @method static Builder| Article newQuery()
 * @method static Builder| Article query()
 * @method static Builder| Article whereCreatedAt($value)
 * @method static Builder| Article whereId($value)
 * @method static Builder| Article whereTitle($value)
 * @method static Builder| Article whereUserId($value)
 *
 */
class Article extends Model
{
    protected $guarded = ['id'];

    public function author()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class, 'articles_tags');
    }

    public function images()
    {
        return $this->morphMany(Image::class, 'imageable');
    }

    public function getPreviewTextAttribute()
    {
        $wrapped = wordwrap($this->text, strlen($this->text) / 5, "wrap_break_str", true);

        $to = strpos($wrapped, "wrap_break_str");
        return substr($wrapped, 0, $to);
    }
}

resources/views/article.blade.php
@extends('layouts.app')

@push('head')
    <link href="{{ asset('css/create_article.css') }}" rel="stylesheet">
@endpush

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="">
                    <div class="text-center">
                        <h4 class="article-title text-capitalize text-left text-decoration-none font-weight-bold"> {{$article->title}} </h4>
                        <div class="text-right small font-italic">By {{$article->author->name}} :
                            <em>{{$article->created_at->format('M d, Y') .' - '. $article->created_at->diffForHumans()}}</em>
                        </div>
                    </div>
                </div>
                <div class="article-card">
                    <div class="card">
                        <div class="card-body text-secondary">

                            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                                <div class="carousel-inner">
                                    @foreach($article->images as $image)
                                        <div
                                            class="carousel-item item {!! isset($active) ? "" : "active"; $active= true; !!}">
                                            <img class="d-block w-100"
                                                 src="{{strpos($image->url, 'articles') !== false ? url($image->url) : url('img/articles/' . $image->url)}}"
                                                 alt="Article Image">
                                        </div>
                                    @endforeach
                                </div>
                                <a class="carousel-control-prev" href="#carouselExampleControls" role="button"
                                   data-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Previous</span>
                                </a>
                                <a class="carousel-control-next" href="#carouselExampleControls" role="button"
                                   data-slide="next">
                                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </div>
                            <div class="article-text">{!! $article->text !!}</div>
                            <div class="tags-card">
                                <ul class="tags-ul">
                                    @foreach($article->tags as $tag)
                                        <a class="d-inline-block btn btn-info border-success tag-item"
                                           href="{{route('article.filter_tag', $tag->name)}}"
                                           target="_blank">{{$tag->name}}</a>
                                    @endforeach
                                </ul>
                            </div>
                        </div>
                        @auth()
                            <div class="card-footer admin-buttons  border-top">
                                <a href="{{route('admin.articles.edit', $article->id)}}" target="_blank"
                                   class="btn btn-info">Update This Article</a>
                                <a onclick="delete_article({{$article->id}});" class="btn btn-danger float-right">Delete
                                    This Article</a>
                            </div>
                        @endauth
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')
@push('head')
    <link href="{{ asset('css/create_article.css') }}" rel="stylesheet">
@endpush
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card"> <!--card -->
                    <div class="text-center card-header"> <!--card header-->
                        <h2>Latest Articles </h2>
                        <small
                            class="border-info">{{ isset($filter_tag) ? " Filter tag (". $filter_tag. ")" : ""}}</small>
                    </div>
                </div>


                @foreach($articles as $article)
                    <div class="article-card border-bottom">
                        <div class="card"><!--card-->
                            <div class="card-header text-left text-capitalize">
                                <a class="text-decoration-none font-weight-bold"
                                   href="{{route('article.show', $article->id)}}" target="_blank">
                                    {{$article->title}}
                                </a>
                            </div>

                            <div class="text-right small font-italic">By {{$article->author->name}} :
                                <em>{{$article->created_at->format('M d, Y') .' - '. $article->created_at->diffForHumans()}}</em>
                            </div>

                            @if($article->images()->count())
                                @php
                                    $img_url = $article->images()->first()->url
                                @endphp
                                <div class="article-img">
                                    <img
                                        src="{{strpos($img_url, 'articles') !== false ? url($img_url) : url('img/articles/' . $img_url)}}"
                                        alt="Main Article Image"/>
                                </div>
                            @endif
                            <div class="card-body text-secondary">
                                <div onclick="show_article({{$article->id}})" class="article-text">
                                    {!! $article->preview_text !!}...
                                </div>
                                <div class="tags-card">
                                    <ul class="tags-ul">
                                        @foreach($article->tags as $tag)
                                            <a class="d-inline-block btn btn-info border-success tag-item"
                                               href="{{route('article.filter_tag', $tag->name)}}"
                                               target="_blank">{{$tag->name}}</a>
                                        @endforeach
                                    </ul>
                                </div>
                            </div>
                            @auth()
                                {{--                                <div class="card-footer admin-buttons">--}}
                                {{--                                    <a href="{{route('admin.articles.edit', $article->id)}}" target="_blank"--}}
                                {{--                                       class="btn btn-info">Update This Article</a>--}}
                                {{--                                    <a onclick="delete_article({{$article->id}});" class="btn btn-danger float-right">Delete--}}
                                {{--                                        This Article</a>--}}
                                {{--                                </div>--}}
                            @endauth
                        </div>
                    </div>
                @endforeach

            </div>
        </div>
    </div>
@endsection