routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/test', function () {
    return phpinfo();
});

//Auth::routes();
// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/', 'ArticlesController@index')->name('home');
Route::get('/articles/{article}', 'ArticlesController@show')->name('article.show');
Route::get('/articles/tagged/{tag}', 'ArticlesController@filter_tag')->name('article.filter_tag');


Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['web', 'auth']], function ($q) {
    Route::resource('articles', 'Admin\ArticlesController')->except(['index', 'show']);
    Route::post('/images/{image_id}/delete', 'Admin\ArticlesController@delete_img')->name('images.delete');
});


Route::any('{catchall}', function (){
    return redirect()->route('home')->setStatusCode(302);
})->where('catchall', '.*');

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

/**
 * Class Article
 * @package App\Models
 *
 * @property int $id
 * @property string $title
 * @property string $text
 * @property-read User|Model $author
 * @property-read Tag[]|Collection $tags
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 *
 * @method static Builder| Article newModelQuery()
 * @method static Builder| Article newQuery()
 * @method static Builder| Article query()
 * @method static Builder| Article whereCreatedAt($value)
 * @method static Builder| Article whereId($value)
 * @method static Builder| Article whereTitle($value)
 * @method static Builder| Article whereUserId($value)
 *
 */
class Article extends Model
{
    protected $guarded = ['id'];

    public function author()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class, 'articles_tags');
    }

    public function images()
    {
        return $this->morphMany(Image::class, 'imageable');
    }

    public function getPreviewTextAttribute()
    {
        $wrapped = wordwrap($this->text, strlen($this->text) / 5, "wrap_break_str", true);

        $to = strpos($wrapped, "wrap_break_str");
        return substr($wrapped, 0, $to);
    }
}

app/Http/Controllers/Admin/ArticlesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helpers\ResourceHelper;
use App\Http\Controllers\Controller;
use App\Http\Requests\CreateArticleRequest;
use App\Http\Requests\updateArticleRequest;
use App\Repositories\Admin\ArticlesRepository;
use App\Repositories\Admin\ImagesRepository;
use App\Repositories\Admin\TagsRepository;
use Illuminate\Support\Facades\DB;

class ArticlesController extends Controller
{

    protected $articlesRepository;
    protected $tagsRepository;
    protected $imagesRepository;

    public function __construct(ArticlesRepository $articlesRepository, TagsRepository $tagsRepository, ImagesRepository $imagesRepository)
    {
        $this->articlesRepository = $articlesRepository;
        $this->tagsRepository = $tagsRepository;
        $this->imagesRepository = $imagesRepository;
    }


    public function create()
    {
        $tags = $this->tagsRepository->all();
        return view('admin.articles.create', compact('tags'));
    }


    public function store(CreateArticleRequest $request)
    {
        try {
            $images = ResourceHelper::upload_all_image($request);
            $this->articlesRepository->create($request->only(['title', 'wysiwyg-editor']), $request->get('tags'), $images);
            return redirect()->route('home')->withFlashSuccess("Article Created Successfully");
        } catch (\Exception $exception) {
            return back()->withInput()->withFlashDanger($exception->getMessage());
        }
    }


    public function edit($id)
    {
        $article = $this->articlesRepository->getById($id);
        $tags = $this->tagsRepository->all();
        $article_tags = $article->tags()->pluck('tags.id')->toArray();

        return view('admin.articles.edit', compact('article', 'tags', 'article_tags'));
    }


    public function update(updateArticleRequest $request, $id)
    {

        try {
            $images = ResourceHelper::upload_all_image($request);
            $article = $this->articlesRepository->getById($id);
            $this->articlesRepository->update($article, $request->only(['title', 'wysiwyg-editor']), $request->get('tags'), $images);
            return redirect()->route('home')->withFlashSuccess("Article Updated Successfully");
        } catch (\Exception $exception) {
            return back()->withInput()->withFlashDanger($exception->getMessage());
        }
    }


    public function destroy($id)
    {
        try {
            $deleted = $this->articlesRepository->deleteById($id);
            return response()->json(['message' => $deleted ? 'Article deleted!' : 'Failed to delete.']);
        }catch (\Exception $exception){
            return response()->json(['message' => $exception->getMessage()]);
        }
    }

    public function delete_img($image_id)
    {
        $image = $this->imagesRepository->getById($image_id);
        $image_url = strpos($image->url, 'articles') !== false ? $image->url : 'img/articles/' . $image->url;
        if (unlink(public_path($image_url))) {
            $image->delete();
            return response()->json(['message' => 'Success']);
        }
        return response()->json(['message' => 'Failed'], 500);
    }
}

app/Http/Controllers/ArticlesController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Repositories\Admin\ArticlesRepository;
use Illuminate\Http\Request;

class ArticlesController extends Controller
{
    protected $articlesRepository;

    public function __construct(ArticlesRepository $articlesRepository)
    {
        $this->articlesRepository = $articlesRepository;
    }


    public function index()
    {
        $data = $this->articlesRepository->orderBy('updated_at', 'desc')->get();

        return view('home', ['articles' => $data]);
    }


    public function show(int $id)
    {
        $article = $this->articlesRepository->with(['tags', 'images'])->getById($id);

        return view('article', compact('article'));
    }

    public function filter_tag(string $tag)
    {
        $data = $this->articlesRepository->byTag($tag);

        return view('home', ['articles' => $data , 'filter_tag' => $tag]);
    }

}

resources/views/admin/articles/create.blade.php
@extends('layouts.app')

@push('head')
    <script src="{{ asset('js/create_article.js') }}" defer></script>
    <link href="{{ asset('css/create_article.css') }}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js" defer></script>
    <script src="//cdn.ckeditor.com/4.16.0/standard/ckeditor.js"></script>
@endpush

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <div class="text-center">Post New Article</div>
                    </div>

                    <form action="{{route('admin.articles.store')}}" method="post" enctype="multipart/form-data">
                        <div class="card-body">
                            {{csrf_field()}}
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input class="form-control" placeholder="Article Title" type="text"
                                       max="191" name="title"
                                       id="title" required>
                            </div>

                            <div class="form-group">
                                <label for="wysiwyg-editor">Article Paragraph</label>
                                <div class="form-group">
                                    <textarea class="ckeditor form-control" name="wysiwyg-editor"></textarea>
                                </div>
                            </div>

                            <div class="form-group m-auto" id="select-tags">
                                <label for="choices-multiple-tags">Tags</label>
                                <select class="form-control" name="tags[]" id="choices-multiple-tags" multiple name="tags[]" required>
                                    @foreach($tags as $tag)
                                        <option value="{{$tag->id}}">{{$tag->name}}</option>
                                    @endforeach
                                </select>
                            </div>

                            <!-- Images upload -->
                            <div class="form-group mt-4">
                                <label for="images">Images</label>
                                <div class="row">
                                    <div class="col-sm-2 col-md-3 imgUp">
                                        <div class="imagePreview"></div>
                                        <label class="btn btn-primary">
                                            Upload <input type="file" name="images[]" class="uploadFile img" value="Upload Photo"
                                                         style="width: 0px;height: 0px;overflow: hidden;">
                                        </label>
                                    </div><!-- col-2 -->
                                    <i class="fa fa-plus imgAdd"></i>
                                </div><!-- row -->
                            </div><!-- container -->

                        </div>
                        <div class="card-footer border-top">
                            <button type="submit" class="btn btn-info">Post</button>
                            <button onclick="history.back()" class="btn btn-danger float-right">Cancel</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/articles/edit.blade.php
@extends('layouts.app')

@push('head')
    <script src="{{ asset('js/create_article.js') }}" defer></script>
    <link href="{{ asset('css/create_article.css') }}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js" defer></script>
    <script src="//cdn.ckeditor.com/4.16.0/standard/ckeditor.js"></script>
@endpush

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <div class="text-center">Update Article</div>
                    </div>

                    <form action="{{route('admin.articles.update', $article)}}" method="post"
                          enctype="multipart/form-data">
                        @method('PUT')
                        <div class="card-body">
                            {{csrf_field()}}
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input class="form-control" placeholder="Article Title" type="text"
                                       max="191" name="title" value="{{$article->title}}"
                                       id="title" required>
                            </div>

                            <div class="form-group">
{{--                                <label for="text">Article Paragraph</label>--}}
{{--                                <textarea class="form-control" name="text" id="text" rows="8"--}}
{{--                                          placeholder="Article Paragraph" required> {{$article->text}}</textarea>--}}
                                <label for="wysiwyg-editor">Article Paragraph</label>
                                <div class="form-group">
                                    <textarea class="ckeditor form-control" name="wysiwyg-editor">{!! $article->text !!}</textarea>
                                </div>
                            </div>

                            <div class="form-group m-auto" id="select-tags">
                                <label for="choices-multiple-tags">Tags</label>
                                <select class="form-control" name="tags[]" id="choices-multiple-tags" multiple
                                        name="tags[]" required>
                                    @foreach($tags as $tag)
                                        <option
                                            value="{{$tag->id}}" {{in_array($tag->id, $article_tags) ? "selected" :""}}>{{$tag->name}}</option>
                                    @endforeach
                                </select>
                            </div>

                            <!-- Existing Images -->
                            <label class="d-block mt-3" for="#">Images</label>
                            <div class="images-collection d-inline-flex row">
                                @foreach($article->images as $image)

                                    <div class="img-wrap">
                                        <span class="close article_img_del"><i class="fas fa-trash" id="{{$image->id}}"></i></span>
                                        <img alt="Image" width="200" src="{{strpos($image->url, 'articles') !== false ? url($image->url) : url('img/articles/' . $image->url)}}" />
                                    </div>
                                @endforeach
                            </div>
                            <!-- Images upload -->
                            <div class="form-group mt-4">
                                <div class="row">
                                    <div class="col-sm-2 col-md-3 imgUp">
                                        <div class="imagePreview"></div>
                                        <label class="btn btn-primary">
                                            Upload <input type="file" name="images[]" class="uploadFile img"
                                                          value="Upload Photo"
                                                          style="width: 0px;height: 0px;overflow: hidden;">
                                        </label>
                                    </div><!-- col-2 -->
                                    <i class="fa fa-plus imgAdd"></i>
                                </div><!-- row -->
                            </div><!-- container -->

                        </div>
                        <div class="card-footer border-top">
                            <button type="submit" class="btn btn-info btn-dark">Update</button>
                            <button onclick="history.back()" class="btn btn-danger float-right">Cancel</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection